/**
 * GENERATED by scripts/gen-category-vocab.mjs — do not edit.
 *
 * Projection of public.material_categories. Regenerate after changing controlled_vocab or
 * vocab_aliases; tests/unit/categoryVocabRegistry.test.ts fails the build when this is stale
 * or when a second copy of the vocabulary appears in hand-written source (#347 phase 3.4).
 */

export interface CategoryVocabEntry {
  key: string;
  displayName: string;
  /** Canonical values a model may emit for this category. */
  controlledVocab: string[];
  /** Coarse terms that map ONTO this category. Never offered to a model as a choice. */
  aliases: string[];
}

export const CATEGORY_VOCAB: CategoryVocabEntry[] = [
  {
    key: 'appliances',
    displayName: 'Appliances',
    controlledVocab: ['dishwasher', 'dryer', 'extractor', 'hob', 'microwave', 'oven', 'refrigerator', 'washing_machine'],
    aliases: ['appliances', 'syskeves', 'white_goods'],
  },
  {
    key: 'building_materials',
    displayName: 'Building Materials',
    controlledVocab: ['admixture', 'aggregate', 'brick', 'cement', 'concrete_block', 'expanding_foam', 'grout', 'lintel', 'mortar', 'plaster', 'primer', 'rebar', 'rebar_mesh', 'render', 'sand', 'screed', 'sealant', 'tile_adhesive', 'waterproofing'],
    aliases: ['aggregates', 'building_materials', 'cement', 'construction_chemicals', 'domika_ylika', 'masonry', 'mortar'],
  },
  {
    key: 'decor',
    displayName: 'Decor',
    controlledVocab: ['candle_holder', 'curtain', 'cushion', 'mirror', 'planter', 'rug', 'sculpture', 'vase', 'wall_art'],
    aliases: ['decor'],
  },
  {
    key: 'drywall',
    displayName: 'Drywall & Partitions',
    controlledVocab: ['access_panel', 'ceiling_channel', 'corner_bead', 'drywall_screw', 'joint_compound', 'jointing_mesh', 'metal_profile', 'plasterboard'],
    aliases: ['drywall', 'gypsosanida', 'gypsum', 'plasterboard'],
  },
  {
    key: 'electrical',
    displayName: 'Electrical',
    controlledVocab: ['cable', 'cable_gland', 'cable_tray', 'circuit_breaker', 'conduit', 'data_outlet', 'distribution_board', 'doorbell_intercom', 'driver_transformer', 'junction_box', 'led_profile', 'rcd', 'socket_outlet', 'trunking', 'wall_switch'],
    aliases: ['electric', 'electrical', 'ilektrologika', 'switchgear', 'wiring'],
  },
  {
    key: 'furniture',
    displayName: 'Furniture',
    controlledVocab: ['accent_chair', 'armchair', 'bed', 'cabinet', 'coffee_table', 'desk', 'dining_chair', 'dining_table', 'outdoor_furniture', 'shelving', 'side_table', 'sideboard', 'sofa'],
    aliases: ['furniture'],
  },
  {
    key: 'general_materials',
    displayName: 'General Materials',
    controlledVocab: ['cladding', 'composite', 'concrete', 'countertop', 'fabric_swatch', 'glass_panel', 'leather_swatch', 'metal_panel', 'quartz', 'stone_slab', 'terrazzo'],
    aliases: ['granite', 'marble', 'stone'],
  },
  {
    key: 'hardware',
    displayName: 'Hardware & Ironmongery',
    controlledVocab: ['bracket', 'catch', 'drawer_box', 'drawer_runner', 'fixing', 'furniture_leg', 'handle', 'hanging_rail', 'hinge', 'knob', 'lock', 'screw'],
    aliases: ['exartimata', 'fittings', 'hardware', 'ironmongery'],
  },
  {
    key: 'heating',
    displayName: 'Heating',
    controlledVocab: ['boiler', 'convector', 'fireplace', 'heat_pump', 'radiator', 'towel_rail', 'underfloor_heating'],
    aliases: ['heating'],
  },
  {
    key: 'hvac',
    displayName: 'Ventilation & Air Conditioning',
    controlledVocab: ['air_conditioner', 'diffuser', 'duct', 'extract_fan', 'grille', 'mvhr_unit'],
    aliases: ['air_conditioning', 'hvac', 'klimatismos', 'ventilation'],
  },
  {
    key: 'insulation',
    displayName: 'Insulation',
    controlledVocab: ['acoustic_insulation', 'eps', 'mineral_wool', 'pir_board', 'reflective_membrane', 'xps'],
    aliases: ['insulation', 'monosi'],
  },
  {
    key: 'kitchen',
    displayName: 'Kitchen',
    controlledVocab: ['kitchen_appliance', 'kitchen_cabinet', 'kitchen_handle', 'kitchen_hood', 'kitchen_organiser', 'kitchen_sink', 'kitchen_tap', 'kitchen_worktop'],
    aliases: ['kitchen'],
  },
  {
    key: 'lighting',
    displayName: 'Lighting',
    controlledVocab: ['ceiling_light', 'chandelier', 'floor_lamp', 'lamp', 'lighting', 'outdoor_light', 'pendant_light', 'recessed_light', 'spotlight', 'table_lamp', 'track_light', 'wall_light'],
    aliases: ['lighting'],
  },
  {
    key: 'openings',
    displayName: 'Doors, Windows & Openings',
    controlledVocab: ['door_frame', 'entrance_door', 'fire_door', 'garage_door', 'glass_partition', 'interior_door', 'roof_window', 'shutter', 'sliding_door', 'window'],
    aliases: ['door', 'door_window', 'doors', 'fenestration', 'joinery', 'openings', 'windows'],
  },
  {
    key: 'paint_wall_decor',
    displayName: 'Paint & Wall Coverings',
    controlledVocab: ['decorative_plaster', 'wall_coating', 'wall_paint', 'wall_panel', 'wallpaper'],
    aliases: ['paint'],
  },
  {
    key: 'panel_boards',
    displayName: 'Panel Boards & Edging',
    controlledVocab: ['chipboard', 'edge_tape', 'hpl', 'mdf', 'melamine_board', 'osb', 'plywood', 'veneer', 'worktop_blank'],
    aliases: ['boards', 'edgebanding', 'melamine', 'panel_boards'],
  },
  {
    key: 'plumbing',
    displayName: 'Plumbing & Pipework',
    controlledVocab: ['expansion_vessel', 'floor_drain', 'manifold', 'pipe', 'pipe_fitting', 'pipe_insulation', 'pump', 'siphon', 'valve', 'water_filter'],
    aliases: ['pipework', 'plumbing', 'ydravlika'],
  },
  {
    key: 'sanitary',
    displayName: 'Sanitary',
    controlledVocab: ['basin', 'bathtub', 'bidet', 'faucet', 'mixer', 'shower_enclosure', 'shower_head', 'shower_tray', 'tap', 'toilet', 'urinal', 'vanity_unit', 'whirlpool_bath'],
    aliases: ['sanitary'],
  },
  {
    key: 'tiles',
    displayName: 'Tiles',
    controlledVocab: ['bathroom_tile', 'ceramic_tile', 'floor_tile', 'porcelain_tile', 'shower_tile', 'wall_tile'],
    aliases: ['ceramic', 'ceramic_tile', 'floor_tile', 'mosaic', 'mosaic_tile', 'porcelain', 'porcelain_tile', 'tile', 'wall_tile'],
  },
  {
    key: 'tools',
    displayName: 'Tools & Site Equipment',
    controlledVocab: ['access_equipment', 'cutting_consumable', 'hand_tool', 'measuring', 'power_tool', 'ppe', 'site_equipment'],
    aliases: ['ergaleia', 'tools'],
  },
  {
    key: 'wellness',
    displayName: 'Sauna, Spa & Wellness',
    controlledVocab: ['hammam_steam_room', 'hydromassage_shower_panel', 'infrared_cabin', 'sauna_accessory', 'sauna_cabin', 'sauna_control_unit', 'sauna_heater', 'spa_hot_tub', 'steam_generator'],
    aliases: ['hammam', 'hot_tub', 'hydromassage', 'jacuzzi', 'sauna', 'spa', 'steam_room', 'turkish_bath', 'wellness'],
  },
  {
    key: 'wood',
    displayName: 'Wood',
    controlledVocab: ['carpet', 'engineered_wood', 'hardwood', 'laminate', 'parquet', 'vinyl_flooring', 'wood_flooring'],
    aliases: ['bamboo', 'wood'],
  },
];

/**
 * Every category key, as a literal tuple so `UploadCategory` can be a type rather than a
 * hand-written union that drifts. `building_materials` was live in the DB and absent from
 * the union for months, so a door resolved to `general_materials` and rendered under the
 * wrong heading (#368 PD-5).
 */
export const CATEGORY_KEYS = ['appliances', 'building_materials', 'decor', 'drywall', 'electrical', 'furniture', 'general_materials', 'hardware', 'heating', 'hvac', 'insulation', 'kitchen', 'lighting', 'openings', 'paint_wall_decor', 'panel_boards', 'plumbing', 'sanitary', 'tiles', 'tools', 'wellness', 'wood'] as const;

export type CategoryKey = typeof CATEGORY_KEYS[number];

/** Display name per category key, straight from material_categories. */
export const CATEGORY_DISPLAY_NAMES: Record<string, string> = Object.fromEntries(
  CATEGORY_VOCAB.map((c) => [c.key, c.displayName]),
);

/** Every canonical value across all categories. */
export const ALL_CONTROLLED_VOCAB: ReadonlySet<string> = new Set(
  CATEGORY_VOCAB.flatMap((c) => c.controlledVocab),
);

/**
 * Resolve a fine-grained or loose material_category value onto a category key.
 * Canonical values win over aliases, so a term that is both resolves the same way every time.
 */
export function categoryKeyForVocab(value: string): string | null {
  const v = value.trim().toLowerCase();
  if (!v) return null;
  for (const c of CATEGORY_VOCAB) if (c.controlledVocab.includes(v)) return c.key;
  for (const c of CATEGORY_VOCAB) if (c.aliases.includes(v)) return c.key;
  return null;
}
