/**
 * GENERATED by scripts/gen-category-vocab.mjs — do not edit.
 *
 * Projection of public.material_categories. Regenerate after changing controlled_vocab or
 * vocab_aliases; tests/unit/categoryVocabRegistry.test.ts fails the build when this is stale
 * or when a second copy of the vocabulary appears in hand-written source (#347 phase 3.4).
 */

export interface CategoryVocabEntry {
  key: string;
  displayName: string;
  /** Canonical values a model may emit for this category. */
  controlledVocab: string[];
  /** Coarse terms that map ONTO this category. Never offered to a model as a choice. */
  aliases: string[];
}

export const CATEGORY_VOCAB: CategoryVocabEntry[] = [
  {
    key: 'building_materials',
    displayName: 'Building Materials',
    controlledVocab: ['door', 'window'],
    aliases: [],
  },
  {
    key: 'decor',
    displayName: 'Decor',
    controlledVocab: ['candle_holder', 'curtain', 'cushion', 'mirror', 'planter', 'rug', 'sculpture', 'vase', 'wall_art'],
    aliases: ['decor'],
  },
  {
    key: 'furniture',
    displayName: 'Furniture',
    controlledVocab: ['accent_chair', 'armchair', 'bed', 'cabinet', 'coffee_table', 'desk', 'dining_chair', 'dining_table', 'outdoor_furniture', 'shelving', 'side_table', 'sideboard', 'sofa'],
    aliases: ['furniture'],
  },
  {
    key: 'general_materials',
    displayName: 'General Materials',
    controlledVocab: ['cladding', 'composite', 'concrete', 'countertop', 'fabric_swatch', 'glass_panel', 'leather_swatch', 'metal_panel', 'quartz', 'stone_slab', 'terrazzo'],
    aliases: ['granite', 'marble', 'stone'],
  },
  {
    key: 'heating',
    displayName: 'Heating',
    controlledVocab: ['boiler', 'convector', 'fireplace', 'heat_pump', 'radiator', 'towel_rail', 'underfloor_heating'],
    aliases: ['heating'],
  },
  {
    key: 'kitchen',
    displayName: 'Kitchen',
    controlledVocab: ['kitchen_appliance', 'kitchen_cabinet', 'kitchen_handle', 'kitchen_hood', 'kitchen_organiser', 'kitchen_sink', 'kitchen_tap', 'kitchen_worktop'],
    aliases: ['kitchen'],
  },
  {
    key: 'lighting',
    displayName: 'Lighting',
    controlledVocab: ['ceiling_light', 'chandelier', 'floor_lamp', 'lighting', 'outdoor_light', 'pendant_light', 'recessed_light', 'spotlight', 'table_lamp', 'track_light', 'wall_light'],
    aliases: ['lighting'],
  },
  {
    key: 'paint_wall_decor',
    displayName: 'Paint / Wall Decors',
    controlledVocab: ['decorative_plaster', 'wall_coating', 'wall_paint', 'wall_panel', 'wallpaper'],
    aliases: ['paint'],
  },
  {
    key: 'sanitary',
    displayName: 'Sanitary',
    controlledVocab: ['basin', 'bathtub', 'bidet', 'faucet', 'mixer', 'shower_enclosure', 'shower_head', 'shower_tray', 'tap', 'toilet', 'urinal', 'vanity_unit'],
    aliases: ['sanitary'],
  },
  {
    key: 'tiles',
    displayName: 'Tiles',
    controlledVocab: ['bathroom_tile', 'ceramic_tile', 'floor_tile', 'porcelain_tile', 'shower_tile', 'wall_tile'],
    aliases: ['ceramic', 'porcelain', 'tile'],
  },
  {
    key: 'wood',
    displayName: 'Wood',
    controlledVocab: ['carpet', 'engineered_wood', 'hardwood', 'laminate', 'parquet', 'vinyl_flooring', 'wood_flooring'],
    aliases: ['bamboo', 'wood'],
  },
];

/** Every canonical value across all categories. */
export const ALL_CONTROLLED_VOCAB: ReadonlySet<string> = new Set(
  CATEGORY_VOCAB.flatMap((c) => c.controlledVocab),
);

/**
 * Resolve a fine-grained or loose material_category value onto a category key.
 * Canonical values win over aliases, so a term that is both resolves the same way every time.
 */
export function categoryKeyForVocab(value: string): string | null {
  const v = value.trim().toLowerCase();
  if (!v) return null;
  for (const c of CATEGORY_VOCAB) if (c.controlledVocab.includes(v)) return c.key;
  for (const c of CATEGORY_VOCAB) if (c.aliases.includes(v)) return c.key;
  return null;
}
