/**
 * Priced schedules — a bill of quantities: rates against measured quantities.
 *
 * `amount` is a GENERATED column in the database and is therefore READ-ONLY here. Quantity times
 * rate is a money quantity and it has exactly one implementation; this service never computes it,
 * never sends it, and a schedule total is the sum of what the database returned.
 *
 * ONE CONTRACT SCHEDULE PER PROJECT, enforced by a partial unique index. When an accepted contract
 * schedule exists it IS the contract sum and `get_project_cvr` ignores accepted quotes entirely —
 * a contractor who has priced a BoQ has one contract sum, and the quotes that led to it are
 * working papers.
 */
import { supabase } from '@/integrations/supabase/client';

export { SCHEDULE_STATUSES, isScheduleLive } from '../scheduleVocabulary';
export type { ScheduleStatus } from '../scheduleVocabulary';

import type { ScheduleStatus } from '../scheduleVocabulary';

export interface ProjectSchedule {
  id: string;
  workspace_id: string;
  project_id: string;
  name: string;
  status: ScheduleStatus;
  /** The schedule that IS the contract sum. At most one per project. */
  is_contract: boolean;
  currency: string;
  version: number;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface ScheduleItem {
  id: string;
  workspace_id: string;
  schedule_id: string;
  item_ref: string | null;
  description: string;
  /** A key from `src/lib/units.ts` — the canonical list, not a second one. */
  unit: string | null;
  quantity: number | null;
  rate: number | null;
  /** GENERATED by the database. Never sent, never recomputed. NULL means no rate yet. */
  amount: number | null;
  cost_code_id: string | null;
  /** Money allowed for work not yet defined. In the contract sum, but flagged. */
  is_provisional: boolean;
  notes: string | null;
  sort: number;
}

const SCHEDULE_COLUMNS =
  'id, workspace_id, project_id, name, status, is_contract, currency, version, notes, created_at, updated_at';
const ITEM_COLUMNS =
  'id, workspace_id, schedule_id, item_ref, description, unit, quantity, rate, amount, ' +
  'cost_code_id, is_provisional, notes, sort';

function readable(error: { code?: string; message: string }): Error {
  if (error.code === '23505') {
    return new Error('This project already has a contract schedule. Mark the other one superseded first.');
  }
  if (error.code === '42501') return new Error('You do not have permission to change schedules on this project.');
  if (error.code === '428C9') {
    return new Error('The line total is worked out by the database and cannot be set directly.');
  }
  if (error.code === '23514') return new Error(error.message);
  if (error.code === '23503' && /cost code/i.test(error.message)) return new Error(error.message);
  return new Error(error.message);
}

export const schedulesService = {
  async list(projectId: string): Promise<ProjectSchedule[]> {
    const { data, error } = await supabase
      .from('project_schedules')
      .select(SCHEDULE_COLUMNS)
      .eq('project_id', projectId)
      .order('is_contract', { ascending: false })
      .order('created_at');
    if (error) throw readable(error);
    return (data ?? []) as unknown as ProjectSchedule[];
  },

  async items(scheduleId: string): Promise<ScheduleItem[]> {
    const { data, error } = await supabase
      .from('project_schedule_items')
      .select(ITEM_COLUMNS)
      .eq('schedule_id', scheduleId)
      .order('sort')
      .order('item_ref');
    if (error) throw readable(error);
    return (data ?? []) as unknown as ScheduleItem[];
  },

  async createSchedule(input: {
    workspace_id: string;
    project_id: string;
    name: string;
    is_contract?: boolean;
    currency?: string;
  }): Promise<ProjectSchedule> {
    const name = input.name.trim();
    if (!name) throw new Error('Give the schedule a name.');
    const { data: { user } } = await supabase.auth.getUser();
    const { data, error } = await supabase
      .from('project_schedules')
      .insert({
        workspace_id: input.workspace_id,
        project_id: input.project_id,
        name,
        is_contract: input.is_contract ?? false,
        currency: input.currency ?? 'EUR',
        created_by: user?.id ?? null,
      })
      .select(SCHEDULE_COLUMNS)
      .single();
    if (error) throw readable(error);
    return data as unknown as ProjectSchedule;
  },

  async setStatus(id: string, status: ScheduleStatus): Promise<void> {
    const { error } = await supabase.from('project_schedules').update({ status }).eq('id', id);
    if (error) throw readable(error);
  },

  async setIsContract(id: string, isContract: boolean): Promise<void> {
    const { error } = await supabase.from('project_schedules').update({ is_contract: isContract }).eq('id', id);
    if (error) throw readable(error);
  },

  async removeSchedule(id: string): Promise<void> {
    const { error } = await supabase.from('project_schedules').delete().eq('id', id);
    if (error) throw readable(error);
  },

  async addItem(input: {
    workspace_id: string;
    schedule_id: string;
    description: string;
    item_ref?: string | null;
    unit?: string | null;
    quantity?: number | null;
    rate?: number | null;
    cost_code_id?: string | null;
    is_provisional?: boolean;
    sort?: number;
  }): Promise<ScheduleItem> {
    const description = input.description.trim();
    if (!description) throw new Error('Describe the item of work.');
    const { data, error } = await supabase
      .from('project_schedule_items')
      .insert({
        workspace_id: input.workspace_id,
        schedule_id: input.schedule_id,
        description,
        item_ref: input.item_ref?.trim() || null,
        unit: input.unit || null,
        quantity: input.quantity ?? null,
        rate: input.rate ?? null,
        cost_code_id: input.cost_code_id ?? null,
        is_provisional: input.is_provisional ?? false,
        sort: input.sort ?? 0,
        // `amount` is deliberately absent — it is generated, and Postgres refuses a write to it.
      })
      .select(ITEM_COLUMNS)
      .single();
    if (error) throw readable(error);
    return data as unknown as ScheduleItem;
  },

  async updateItem(id: string, patch: Partial<Pick<ScheduleItem,
    'item_ref' | 'description' | 'unit' | 'quantity' | 'rate' | 'cost_code_id' | 'is_provisional' | 'notes' | 'sort'
  >>): Promise<void> {
    const { error } = await supabase.from('project_schedule_items').update(patch).eq('id', id);
    if (error) throw readable(error);
  },

  async removeItem(id: string): Promise<void> {
    const { error } = await supabase.from('project_schedule_items').delete().eq('id', id);
    if (error) throw readable(error);
  },
};
