import React, { useEffect, useRef, useState } from 'react';
import { Ruler, Check, RotateCcw, TriangleAlert } from 'lucide-react';
import { Button } from '@/components/core/ui/button';
import { Input } from '@/components/core/ui/input';
import { AnnotationLayer, type NormalizedPoint } from '@/components/features/sheets/AnnotationLayer';
import {
  withCalibration,
  mmPerPx,
  impliedAreaSqm,
  checkAreaAgainstBrief,
  type PlanGeometry,
} from '@/utils/planGeometry';

/**
 * Calibrate a plan backdrop — the step that turns a picture into measurements.
 *
 * The user draws one line across something whose real length they know (a door,
 * a wall, a printed dimension) and types that length. mm-per-pixel falls out.
 *
 * This is the ONLY way scale gets established, deliberately. Every backdrop we
 * can obtain is a raster: uploaded by the user, or generated by Gemini through
 * `floor-plan-text`. The generated ones DRAW dimension callouts because the
 * prompt asks for them, but an image generator writes plausible numbers rather
 * than accurate ones — reading them back would bake a hallucination into every
 * cable run and pipe size downstream.
 *
 * Two details that exist to stop wrong numbers rather than to look nice:
 *   • the length input carries an explicit mm/m unit toggle, because typing "4"
 *     where 4000 was meant is the single most likely calibration mistake and it
 *     scales every derived area by a millionth;
 *   • calibration points are stored against the image's NATURAL pixel size, not
 *     the rendered size, so resizing the window cannot silently change scale.
 */

interface PlanCalibrationCanvasProps {
  imageUrl: string;
  geometry: PlanGeometry;
  onChange: (geometry: PlanGeometry) => void;
  /**
   * Floor area the brief asked for, when known (the agent floor-plan path
   * captures it). Used only to warn on an implausible calibration — never to
   * correct one, since the plan may legitimately cover more than the brief.
   */
  expectedSqm?: number | null;
  disabled?: boolean;
}

type LengthUnit = 'mm' | 'm';

export function PlanCalibrationCanvas({
  imageUrl,
  geometry,
  onChange,
  expectedSqm,
  disabled = false,
}: PlanCalibrationCanvasProps) {
  const [naturalSize, setNaturalSize] = useState<{ w: number; h: number } | null>(null);
  const [p1, setP1] = useState<NormalizedPoint | null>(null);
  const [p2, setP2] = useState<NormalizedPoint | null>(null);
  const [lengthInput, setLengthInput] = useState('');
  const [unit, setUnit] = useState<LengthUnit>('mm');
  const [error, setError] = useState<string | null>(null);
  const imgRef = useRef<HTMLImageElement | null>(null);

  // Natural dimensions are the stable basis for the stored calibration.
  useEffect(() => {
    if (!imageUrl) return;
    const img = new Image();
    imgRef.current = img;
    img.onload = () => setNaturalSize({ w: img.naturalWidth, h: img.naturalHeight });
    img.onerror = () => setError('Could not load the plan image.');
    img.src = imageUrl;
    return () => { img.onload = null; img.onerror = null; };
  }, [imageUrl]);

  const scale = mmPerPx(geometry);
  const impliedArea = naturalSize && scale ? impliedAreaSqm(naturalSize.w, naturalSize.h, scale) : null;
  const areaCheck = impliedArea && expectedSqm ? checkAreaAgainstBrief(impliedArea, expectedSqm) : null;

  const handleClick = (p: NormalizedPoint) => {
    if (disabled) return;
    setError(null);
    // Third click starts a fresh line rather than silently extending the old one.
    if (!p1 || (p1 && p2)) { setP1(p); setP2(null); return; }
    setP2(p);
  };

  const handleApply = () => {
    if (!naturalSize || !p1 || !p2) return;
    const raw = Number(lengthInput);
    if (!Number.isFinite(raw) || raw <= 0) {
      setError('Enter the real length of the line you drew.');
      return;
    }
    const realMm = unit === 'm' ? raw * 1000 : raw;
    const next = withCalibration(geometry, {
      x1: p1.x * naturalSize.w,
      y1: p1.y * naturalSize.h,
      x2: p2.x * naturalSize.w,
      y2: p2.y * naturalSize.h,
      real_mm: realMm,
    });
    if (!next) {
      // withCalibration returns null rather than a zero scale — surface why.
      setError('That line is too short to measure. Draw it across a longer known distance.');
      return;
    }
    setError(null);
    onChange(next);
  };

  const handleReset = () => {
    setP1(null);
    setP2(null);
    setLengthInput('');
    setError(null);
    const { scale: _dropped, ...rest } = geometry;
    onChange(rest as PlanGeometry);
  };

  const aspectRatio = naturalSize ? `${naturalSize.w}/${naturalSize.h}` : '4/3';

  return (
    <div className="space-y-3">
      <div className="flex items-center gap-2 text-xs text-muted-foreground">
        <Ruler className="h-3.5 w-3.5" />
        {!p1 && <span>Click one end of something you know the real length of.</span>}
        {p1 && !p2 && <span>Now click the other end.</span>}
        {p1 && p2 && <span>Enter how long that line really is, then apply.</span>}
      </div>

      {imageUrl ? (
        <AnnotationLayer
          imageUrl={imageUrl}
          aspectRatio={aspectRatio}
          onPointerDownPoint={handleClick}
        >
          <svg className="absolute inset-0 w-full h-full pointer-events-none" preserveAspectRatio="none" viewBox="0 0 100 100">
            {p1 && p2 && (
              <line
                x1={p1.x * 100} y1={p1.y * 100}
                x2={p2.x * 100} y2={p2.y * 100}
                stroke="currentColor"
                className="text-primary"
                strokeWidth={0.5}
                vectorEffect="non-scaling-stroke"
              />
            )}
          </svg>
          {[p1, p2].map((p, i) =>
            p ? (
              <div
                key={i}
                className="absolute -translate-x-1/2 -translate-y-1/2 w-3 h-3 rounded-full bg-primary border border-white pointer-events-none"
                style={{ left: `${p.x * 100}%`, top: `${p.y * 100}%` }}
              />
            ) : null,
          )}
        </AnnotationLayer>
      ) : (
        <div className="text-xs text-muted-foreground p-3 border border-dashed rounded">
          Upload or generate a floor plan first.
        </div>
      )}

      <div className="flex items-end gap-2 flex-wrap">
        <div className="flex-1 min-w-[140px]">
          <label className="text-xs text-muted-foreground mb-1 block">Real length of that line</label>
          <div className="flex items-center gap-1">
            <Input
              value={lengthInput}
              onChange={(e) => setLengthInput(e.target.value)}
              placeholder={unit === 'mm' ? 'e.g. 4000' : 'e.g. 4'}
              inputMode="decimal"
              disabled={disabled || !p1 || !p2}
              className="h-8 text-sm"
            />
            {/* Explicit unit choice — "4" vs "4000" is the classic calibration slip. */}
            <div className="flex rounded-full border border-white/15 overflow-hidden shrink-0">
              {(['mm', 'm'] as LengthUnit[]).map((u) => (
                <button
                  key={u}
                  type="button"
                  onClick={() => setUnit(u)}
                  className={`px-2.5 py-1 text-xs ${unit === u ? 'bg-primary text-primary-foreground' : 'text-muted-foreground'}`}
                >
                  {u}
                </button>
              ))}
            </div>
          </div>
        </div>
        <Button
          size="sm"
          className="gap-2"
          onClick={handleApply}
          disabled={disabled || !p1 || !p2 || !lengthInput}
        >
          <Check className="h-4 w-4" />
          Apply scale
        </Button>
        {scale && (
          <Button size="sm" variant="ghost" className="gap-2" onClick={handleReset} disabled={disabled}>
            <RotateCcw className="h-4 w-4" />
            Recalibrate
          </Button>
        )}
      </div>

      {error && (
        <div className="text-xs text-red-400 p-2 rounded border border-red-500/30 bg-red-500/10">
          {error}
        </div>
      )}

      {scale && naturalSize && (
        <div className="text-xs space-y-1 p-2 rounded border border-white/10">
          <div className="text-muted-foreground">
            Scale <span className="text-foreground font-medium">{scale.toFixed(2)} mm/px</span>
            {' · '}
            Plan covers{' '}
            <span className="text-foreground font-medium">
              {(naturalSize.w * scale / 1000).toFixed(2)} × {(naturalSize.h * scale / 1000).toFixed(2)} m
            </span>
            {impliedArea !== null && (
              <> {' · '}<span className="text-foreground font-medium">{impliedArea.toFixed(1)} m²</span></>
            )}
          </div>
          {areaCheck?.suspicious && (
            <div className="flex items-start gap-1.5 text-amber-400">
              <TriangleAlert className="h-3.5 w-3.5 mt-0.5 shrink-0" />
              <span>
                This scale implies {areaCheck.implied_sqm.toFixed(1)} m² but the brief said{' '}
                {areaCheck.expected_sqm.toFixed(1)} m² — {areaCheck.ratio > 1
                  ? `${areaCheck.ratio.toFixed(0)}× larger`
                  : `${(1 / areaCheck.ratio).toFixed(0)}× smaller`}
                . Check the length and unit you entered.
              </span>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
