/* eslint-disable */
// AUTO-GENERATED by scripts/gen-generation-models.mjs — DO NOT EDIT BY HAND.
// Projection of public.generation_models (issue #4 Phase 1). Regenerate after any registry change:
//     SUPABASE_SERVICE_ROLE_KEY=... npm run models:generate
//
// This carries ROUTING only. Money lives in ai_model_pricing, reached via pricing_key — the
// registry deliberately does not hold a second copy of any price. A null pricing_key means the
// model has NO verified cost anywhere and was left unpriced rather than seeded with a guess.

export interface GenerationModelRow {
  id: string;
  display_name: string;
  capability: 'image' | 'video' | '3d' | 'audio' | 'upscale' | 'bg_removal' | 'lipsync';
  sub_capability: string | null;
  provider: string;
  slug: string | null;
  version: string | null;
  adapter: string | null;
  input_requirements: {
    needs_prompt?: boolean;
    min_images?: number;
    max_images?: number;
    image_roles?: string[];
  };
  pricing_key: string | null;
  tier: 'budget' | 'standard' | 'premium' | null;
  status: 'active' | 'degraded' | 'dead';
  enabled: boolean;
  sort_order: number;
}

export const GENERATION_MODELS: readonly GenerationModelRow[] = [
  {
    "id": "gemini-3.1-flash-image",
    "display_name": "Gemini 3.1 Flash Image",
    "capability": "image",
    "sub_capability": "text-or-image-to-image",
    "provider": "google",
    "slug": "gemini-3.1-flash-image",
    "version": null,
    "adapter": "gemini",
    "input_requirements": {
      "max_images": 2,
      "min_images": 0,
      "image_roles": [
        "source",
        "style_reference"
      ],
      "needs_prompt": true
    },
    "pricing_key": "gemini-3.1-flash-image",
    "tier": "budget",
    "status": "active",
    "enabled": true,
    "sort_order": 10
  },
  {
    "id": "gemini-3-pro-image",
    "display_name": "Gemini 3 Pro Image (Nano Banana Pro)",
    "capability": "image",
    "sub_capability": "text-or-image-to-image",
    "provider": "google",
    "slug": "gemini-3-pro-image",
    "version": null,
    "adapter": "gemini",
    "input_requirements": {
      "max_images": 2,
      "min_images": 0,
      "image_roles": [
        "source",
        "style_reference"
      ],
      "needs_prompt": true
    },
    "pricing_key": "gemini-3-pro-image",
    "tier": "premium",
    "status": "active",
    "enabled": true,
    "sort_order": 20
  },
  {
    "id": "xai-aurora",
    "display_name": "Grok Imagine (Aurora)",
    "capability": "image",
    "sub_capability": "text-or-image-to-image",
    "provider": "xai",
    "slug": "grok-imagine-image-quality",
    "version": null,
    "adapter": "grok",
    "input_requirements": {
      "max_images": 2,
      "min_images": 0,
      "image_roles": [
        "source",
        "mask"
      ],
      "needs_prompt": true
    },
    "pricing_key": "xai-aurora",
    "tier": "standard",
    "status": "degraded",
    "enabled": true,
    "sort_order": 30
  },
  {
    "id": "flux-2-pro",
    "display_name": "FLUX.2 Pro",
    "capability": "image",
    "sub_capability": "text-to-image",
    "provider": "replicate",
    "slug": "black-forest-labs/flux-2-pro",
    "version": null,
    "adapter": null,
    "input_requirements": {
      "max_images": 0,
      "min_images": 0,
      "needs_prompt": true
    },
    "pricing_key": "flux-2-pro",
    "tier": "premium",
    "status": "active",
    "enabled": true,
    "sort_order": 40
  },
  {
    "id": "seedream-4",
    "display_name": "Seedream 4",
    "capability": "image",
    "sub_capability": "text-or-image-to-image",
    "provider": "replicate",
    "slug": "bytedance/seedream-4",
    "version": null,
    "adapter": "seedream",
    "input_requirements": {
      "max_images": 1,
      "min_images": 0,
      "image_roles": [
        "source"
      ],
      "needs_prompt": true
    },
    "pricing_key": "seedream-4",
    "tier": "standard",
    "status": "active",
    "enabled": true,
    "sort_order": 45
  },
  {
    "id": "playground-v2.5",
    "display_name": "Playground v2.5",
    "capability": "image",
    "sub_capability": "text-to-image",
    "provider": "replicate",
    "slug": "playgroundai/playground-v2.5-1024px-aesthetic",
    "version": "a45f82a1382bed5c7aeb861dac7c7d191b0fdf74d8d57c4a0e6ed7d4d0bf7d24",
    "adapter": "playground_v25",
    "input_requirements": {
      "max_images": 0,
      "min_images": 0,
      "needs_prompt": true
    },
    "pricing_key": "playground-v2.5",
    "tier": "standard",
    "status": "active",
    "enabled": true,
    "sort_order": 50
  },
  {
    "id": "z-image-turbo",
    "display_name": "Z-Image Turbo",
    "capability": "image",
    "sub_capability": "text-to-image",
    "provider": "replicate",
    "slug": "prunaai/z-image-turbo",
    "version": null,
    "adapter": "z_image",
    "input_requirements": {
      "max_images": 0,
      "min_images": 0,
      "needs_prompt": true
    },
    "pricing_key": "z-image-turbo",
    "tier": "budget",
    "status": "active",
    "enabled": true,
    "sort_order": 55
  },
  {
    "id": "sd3",
    "display_name": "Stable Diffusion 3",
    "capability": "image",
    "sub_capability": "text-to-image",
    "provider": "replicate",
    "slug": "stability-ai/stable-diffusion-3",
    "version": null,
    "adapter": null,
    "input_requirements": {
      "max_images": 0,
      "min_images": 0,
      "needs_prompt": true
    },
    "pricing_key": "stable-diffusion-3",
    "tier": "standard",
    "status": "dead",
    "enabled": false,
    "sort_order": 60
  },
  {
    "id": "adirik-interior-design",
    "display_name": "Adirik Interior Design",
    "capability": "image",
    "sub_capability": "image-to-image",
    "provider": "replicate",
    "slug": "adirik/interior-design",
    "version": "76604baddc85b1b4616e1c6475eca080da339c8875bd4996705440484a6eac38",
    "adapter": "adirik_interior",
    "input_requirements": {
      "max_images": 1,
      "min_images": 1,
      "image_roles": [
        "source"
      ],
      "needs_prompt": true
    },
    "pricing_key": "adirik-interior-design",
    "tier": "standard",
    "status": "active",
    "enabled": true,
    "sort_order": 70
  },
  {
    "id": "comfyui-interior-remodel",
    "display_name": "ComfyUI Interior Remodel",
    "capability": "image",
    "sub_capability": "image-to-image",
    "provider": "replicate",
    "slug": "jschoormans/comfyui-interior-remodel",
    "version": "2a360362540e1f6cfe59c9db4aa8aa9059233d40e638aae0cdeb6b41f3d0dcce",
    "adapter": "comfyui_interior",
    "input_requirements": {
      "max_images": 1,
      "min_images": 1,
      "image_roles": [
        "source"
      ],
      "needs_prompt": true
    },
    "pricing_key": "comfyui-interior-remodel",
    "tier": "standard",
    "status": "active",
    "enabled": true,
    "sort_order": 80
  },
  {
    "id": "interior-v2",
    "display_name": "Interior V2",
    "capability": "image",
    "sub_capability": "image-to-image",
    "provider": "replicate",
    "slug": "jschoormans/interior-v2",
    "version": "8372bd24c6011ea957a0861f0146671eed615e375f038c13259c1882e3c8bac7",
    "adapter": "interior_v2",
    "input_requirements": {
      "max_images": 1,
      "min_images": 1,
      "image_roles": [
        "source"
      ],
      "needs_prompt": true
    },
    "pricing_key": "interior-v2",
    "tier": "standard",
    "status": "active",
    "enabled": true,
    "sort_order": 90
  },
  {
    "id": "interiorly-gen1-dev",
    "display_name": "Interiorly Gen1 Dev",
    "capability": "image",
    "sub_capability": "image-to-image",
    "provider": "replicate",
    "slug": "julian-at/interiorly-gen1-dev",
    "version": "5e3080d1b308e80197b32f0ce638daa8a329d0cf42068739723d8259e44b445e",
    "adapter": "flux_lora_interior",
    "input_requirements": {
      "max_images": 1,
      "min_images": 1,
      "image_roles": [
        "source"
      ],
      "needs_prompt": true
    },
    "pricing_key": "interiorly-gen1-dev",
    "tier": "standard",
    "status": "active",
    "enabled": true,
    "sort_order": 100
  },
  {
    "id": "designer-architecture",
    "display_name": "Designer Architecture",
    "capability": "image",
    "sub_capability": "image-to-image",
    "provider": "replicate",
    "slug": "davisbrown/designer-architecture",
    "version": "0d6f0893b05f14500ce03e45f54290cbffb907d14db49699f2823d0fd35def46",
    "adapter": null,
    "input_requirements": {
      "max_images": 1,
      "min_images": 1,
      "image_roles": [
        "source"
      ],
      "needs_prompt": true
    },
    "pricing_key": "designer-architecture",
    "tier": "standard",
    "status": "active",
    "enabled": true,
    "sort_order": 110
  },
  {
    "id": "erayyavuz-interior-ai",
    "display_name": "Interior AI",
    "capability": "image",
    "sub_capability": "image-to-image",
    "provider": "replicate",
    "slug": "erayyavuz/interior-ai",
    "version": "e299c531485aac511610a878ef44b554381355de5ee032d109fcae5352f39fa9",
    "adapter": "interior_ai",
    "input_requirements": {
      "max_images": 1,
      "min_images": 1,
      "image_roles": [
        "source"
      ],
      "needs_prompt": true
    },
    "pricing_key": "erayyavuz-interior-ai",
    "tier": "standard",
    "status": "degraded",
    "enabled": true,
    "sort_order": 120
  },
  {
    "id": "interor-2",
    "display_name": "Interior 2 (Flux)",
    "capability": "image",
    "sub_capability": "image-to-image",
    "provider": "replicate",
    "slug": "doobls-ai/interor-2",
    "version": "91f2ef63c76a73d2ec4c67cf7b2a9672e074046cf4fde1d98e46a5829f7ea68b",
    "adapter": "flux_lora_interior",
    "input_requirements": {
      "max_images": 1,
      "min_images": 1,
      "image_roles": [
        "source"
      ],
      "needs_prompt": true
    },
    "pricing_key": "interor-2",
    "tier": "budget",
    "status": "active",
    "enabled": true,
    "sort_order": 130
  },
  {
    "id": "colourful-interiors",
    "display_name": "Colourful Interiors (Flux)",
    "capability": "image",
    "sub_capability": "image-to-image",
    "provider": "replicate",
    "slug": "rihan-a/colourful_interiors",
    "version": "ba0425bc2e4bebafa8bd918519fdf3b5a022969a6a7c8ba0746b807bb5b541a3",
    "adapter": "flux_lora_interior",
    "input_requirements": {
      "max_images": 1,
      "min_images": 1,
      "image_roles": [
        "source"
      ],
      "needs_prompt": true
    },
    "pricing_key": "colourful-interiors",
    "tier": "budget",
    "status": "active",
    "enabled": true,
    "sort_order": 140
  },
  {
    "id": "stable-interiors-v2-pb",
    "display_name": "Stable Interiors V2",
    "capability": "image",
    "sub_capability": "image-to-image",
    "provider": "replicate",
    "slug": "pointblack/stable-interiors-v2",
    "version": "569b1bd6e4df6c9c900ad932d4a3a9f05585fac957dc6bc627aa1654853a97b5",
    "adapter": "stable_interiors",
    "input_requirements": {
      "max_images": 1,
      "min_images": 1,
      "image_roles": [
        "source"
      ],
      "needs_prompt": true
    },
    "pricing_key": "stable-interiors-v2-pb",
    "tier": "budget",
    "status": "dead",
    "enabled": false,
    "sort_order": 150
  },
  {
    "id": "stabledesign-interior",
    "display_name": "StableDesign",
    "capability": "image",
    "sub_capability": "image-to-image",
    "provider": "replicate",
    "slug": "melgor/stabledesign_interiordesign",
    "version": "5e13482ea317670bfc797bb18bace359860a721a39b5bbcaa1ffcd241d62bca0",
    "adapter": "stabledesign",
    "input_requirements": {
      "max_images": 1,
      "min_images": 1,
      "image_roles": [
        "source"
      ],
      "needs_prompt": true
    },
    "pricing_key": "stabledesign-interior",
    "tier": "budget",
    "status": "active",
    "enabled": true,
    "sort_order": 155
  },
  {
    "id": "stable-interiors-v2-yz",
    "display_name": "Stable Interiors V2 (Fast)",
    "capability": "image",
    "sub_capability": "image-to-image",
    "provider": "replicate",
    "slug": "youzu/stable-interiors-v2",
    "version": "4836eb257a4fb8b87bac9eacbef9292ee8e1a497398ab96207067403a4be2daf",
    "adapter": "stable_interiors",
    "input_requirements": {
      "max_images": 1,
      "min_images": 1,
      "image_roles": [
        "source"
      ],
      "needs_prompt": true
    },
    "pricing_key": "stable-interiors-v2-yz",
    "tier": "budget",
    "status": "active",
    "enabled": true,
    "sort_order": 160
  },
  {
    "id": "interior-design-sdxl",
    "display_name": "Interior Design SDXL",
    "capability": "image",
    "sub_capability": "image-to-image",
    "provider": "replicate",
    "slug": "rocketdigitalai/interior-design-sdxl",
    "version": "a3c091059a25590ce2d5ea13651fab63f447f21760e50c358d4b850e844f59ee",
    "adapter": "sdxl_interior",
    "input_requirements": {
      "max_images": 1,
      "min_images": 1,
      "image_roles": [
        "source"
      ],
      "needs_prompt": true
    },
    "pricing_key": "interior-design-sdxl",
    "tier": "premium",
    "status": "active",
    "enabled": true,
    "sort_order": 170
  },
  {
    "id": "flux-depth-pro",
    "display_name": "FLUX Depth Pro",
    "capability": "image",
    "sub_capability": "image-to-image",
    "provider": "replicate",
    "slug": "black-forest-labs/flux-depth-pro",
    "version": null,
    "adapter": null,
    "input_requirements": {
      "max_images": 2,
      "min_images": 1,
      "image_roles": [
        "source",
        "style_reference"
      ],
      "needs_prompt": true
    },
    "pricing_key": "flux-depth-pro",
    "tier": "premium",
    "status": "degraded",
    "enabled": true,
    "sort_order": 180
  },
  {
    "id": "proplabs-virtual-staging",
    "display_name": "Virtual Staging",
    "capability": "image",
    "sub_capability": "image-to-image",
    "provider": "proplabs",
    "slug": "virtual-staging",
    "version": null,
    "adapter": "virtual_staging",
    "input_requirements": {
      "max_images": 1,
      "min_images": 1,
      "image_roles": [
        "source"
      ],
      "needs_prompt": false
    },
    "pricing_key": "proplabs-virtual-staging",
    "tier": "standard",
    "status": "active",
    "enabled": true,
    "sort_order": 190
  },
  {
    "id": "wan-3.0-480p",
    "display_name": "Wan3.0 480P",
    "capability": "video",
    "sub_capability": "image-to-video",
    "provider": "alibaba",
    "slug": "wan3.0-video",
    "version": null,
    "adapter": "alibaba",
    "input_requirements": {
      "max_images": 5,
      "min_images": 1,
      "image_roles": [
        "source",
        "reference",
        "last_frame"
      ],
      "needs_prompt": true
    },
    "pricing_key": "wan-3.0-480p",
    "tier": "budget",
    "status": "active",
    "enabled": true,
    "sort_order": 190
  },
  {
    "id": "wan-3.0-720p",
    "display_name": "Wan3.0 720P",
    "capability": "video",
    "sub_capability": "image-to-video",
    "provider": "alibaba",
    "slug": "wan3.0-video",
    "version": null,
    "adapter": "alibaba",
    "input_requirements": {
      "max_images": 5,
      "min_images": 1,
      "image_roles": [
        "source",
        "reference",
        "last_frame"
      ],
      "needs_prompt": true
    },
    "pricing_key": "wan-3.0-720p",
    "tier": "standard",
    "status": "active",
    "enabled": true,
    "sort_order": 192
  },
  {
    "id": "wan-3.0-1080p",
    "display_name": "Wan3.0 1080P",
    "capability": "video",
    "sub_capability": "image-to-video",
    "provider": "alibaba",
    "slug": "wan3.0-video",
    "version": null,
    "adapter": "alibaba",
    "input_requirements": {
      "max_images": 5,
      "min_images": 1,
      "image_roles": [
        "source",
        "reference",
        "last_frame"
      ],
      "needs_prompt": true
    },
    "pricing_key": "wan-3.0-1080p",
    "tier": "premium",
    "status": "active",
    "enabled": true,
    "sort_order": 194
  },
  {
    "id": "seedance-2.5-480p",
    "display_name": "Seedance 2.5 480P",
    "capability": "video",
    "sub_capability": "image-to-video",
    "provider": "bytedance",
    "slug": "dreamina-seedance-2-5-260628",
    "version": null,
    "adapter": "seedance",
    "input_requirements": {
      "max_images": 10,
      "min_images": 1,
      "image_roles": [
        "source",
        "reference",
        "last_frame"
      ],
      "needs_prompt": true
    },
    "pricing_key": "seedance-2.5-480p",
    "tier": "standard",
    "status": "active",
    "enabled": true,
    "sort_order": 196
  },
  {
    "id": "h3-max-480p",
    "display_name": "H3 Max 480p",
    "capability": "video",
    "sub_capability": "image-to-video",
    "provider": "fal",
    "slug": "minimax/h3-max/image-to-video",
    "version": null,
    "adapter": "fal",
    "input_requirements": {
      "max_images": 2,
      "min_images": 0,
      "image_roles": [
        "source",
        "last_frame"
      ],
      "needs_prompt": true
    },
    "pricing_key": "h3-max-480p",
    "tier": "budget",
    "status": "active",
    "enabled": true,
    "sort_order": 197
  },
  {
    "id": "seedance-2.5-720p",
    "display_name": "Seedance 2.5 720P",
    "capability": "video",
    "sub_capability": "image-to-video",
    "provider": "bytedance",
    "slug": "dreamina-seedance-2-5-260628",
    "version": null,
    "adapter": "seedance",
    "input_requirements": {
      "max_images": 10,
      "min_images": 1,
      "image_roles": [
        "source",
        "reference",
        "last_frame"
      ],
      "needs_prompt": true
    },
    "pricing_key": "seedance-2.5-720p",
    "tier": "premium",
    "status": "active",
    "enabled": true,
    "sort_order": 198
  },
  {
    "id": "h3-max-768p",
    "display_name": "H3 Max 768p",
    "capability": "video",
    "sub_capability": "image-to-video",
    "provider": "fal",
    "slug": "minimax/h3-max/image-to-video",
    "version": null,
    "adapter": "fal",
    "input_requirements": {
      "max_images": 2,
      "min_images": 0,
      "image_roles": [
        "source",
        "last_frame"
      ],
      "needs_prompt": true
    },
    "pricing_key": "h3-max-768p",
    "tier": "standard",
    "status": "active",
    "enabled": true,
    "sort_order": 199
  },
  {
    "id": "veo-2",
    "display_name": "Veo 2",
    "capability": "video",
    "sub_capability": "image-to-video",
    "provider": "google",
    "slug": "veo-2",
    "version": null,
    "adapter": "veo",
    "input_requirements": {
      "max_images": 1,
      "min_images": 1,
      "image_roles": [
        "source"
      ],
      "needs_prompt": true
    },
    "pricing_key": "veo-2",
    "tier": "premium",
    "status": "active",
    "enabled": true,
    "sort_order": 200
  },
  {
    "id": "ray-3.2-720p",
    "display_name": "Luma Ray3.2 720p",
    "capability": "video",
    "sub_capability": "image-to-video",
    "provider": "luma",
    "slug": "ray-3.2",
    "version": null,
    "adapter": "luma",
    "input_requirements": {
      "needs_prompt": true,
      "min_images": 0,
      "max_images": 2,
      "image_roles": [
        "source",
        "last_frame"
      ]
    },
    "pricing_key": "ray-3.2-720p",
    "tier": "standard",
    "status": "active",
    "enabled": true,
    "sort_order": 201
  },
  {
    "id": "ray-3.2-1080p",
    "display_name": "Luma Ray3.2 1080p",
    "capability": "video",
    "sub_capability": "image-to-video",
    "provider": "luma",
    "slug": "ray-3.2",
    "version": null,
    "adapter": "luma",
    "input_requirements": {
      "needs_prompt": true,
      "min_images": 0,
      "max_images": 2,
      "image_roles": [
        "source",
        "last_frame"
      ]
    },
    "pricing_key": "ray-3.2-1080p",
    "tier": "premium",
    "status": "active",
    "enabled": true,
    "sort_order": 202
  },
  {
    "id": "kling-v3.0",
    "display_name": "Kling 3.0",
    "capability": "video",
    "sub_capability": "image-to-video",
    "provider": "klingai",
    "slug": "kling-v3-video",
    "version": null,
    "adapter": "kling",
    "input_requirements": {
      "max_images": 1,
      "min_images": 1,
      "image_roles": [
        "source"
      ],
      "needs_prompt": true
    },
    "pricing_key": "kling-3.0",
    "tier": "premium",
    "status": "active",
    "enabled": true,
    "sort_order": 210
  },
  {
    "id": "runway-gen4-turbo",
    "display_name": "Runway Gen-4 Turbo",
    "capability": "video",
    "sub_capability": "image-to-video",
    "provider": "replicate",
    "slug": "runwayml/gen4-turbo",
    "version": null,
    "adapter": null,
    "input_requirements": {
      "max_images": 1,
      "min_images": 1,
      "image_roles": [
        "source"
      ],
      "needs_prompt": true
    },
    "pricing_key": "runway-gen4-turbo",
    "tier": "premium",
    "status": "degraded",
    "enabled": true,
    "sort_order": 220
  },
  {
    "id": "marble-1.1",
    "display_name": "Marble 1.1",
    "capability": "3d",
    "sub_capability": "image-to-world",
    "provider": "worldlabs",
    "slug": "marble-1.1",
    "version": null,
    "adapter": "worldlabs",
    "input_requirements": {
      "max_images": 1,
      "min_images": 1,
      "image_roles": [
        "source"
      ],
      "needs_prompt": false
    },
    "pricing_key": "marble-1.1",
    "tier": "premium",
    "status": "active",
    "enabled": true,
    "sort_order": 310
  }
] as const;

/**
 * SHA-256 of the rows above, as the GENERATOR emitted them.
 *
 * The nightly `dic_detect__generation_registry_projection_stale` catches the database moving
 * without a regeneration. It cannot catch the opposite — this FILE being edited by hand — because
 * it compares the recorded projection against the live table and never sees the file. CI cannot
 * compare the file to the table either: `generation_models` is authenticated-only and no workflow
 * carries a service-role key.
 *
 * So the file carries its own checksum. `tests/unit/generationModelRegistry.test.ts` recomputes it
 * from the array above; a hand-edit changes the rows and not this constant, and the build fails.
 * Between the two, both directions of drift are covered without a secret in CI.
 */
export const PROJECTION_FINGERPRINT = '58069ed422fe735d6e746079178b9283';

/** Model ids the registry knows about, for O(1) membership checks. */
export const GENERATION_MODEL_IDS: ReadonlySet<string> = new Set(
  GENERATION_MODELS.map((m) => m.id),
);

/** Only these should ever be offered in a picker — status/enabled is what the health check writes. */
export function selectableModels(capability?: GenerationModelRow['capability']) {
  return GENERATION_MODELS.filter(
    (m) => m.status === 'active' && m.enabled && (!capability || m.capability === capability),
  );
}
