import { createClient } from '@supabase/supabase-js';
import { corsHeaders } from '../_shared/cors.ts';
import { authenticate } from '../_shared/auth.ts';
import { fetchQuoteData, fetchTemplateConfig, fetchStorageFile } from './data-fetcher.ts';
import { buildQuotePDF } from './pdf-builder.ts';
import type { QuotePDFRequest, QuotePDFResponse } from './types.ts';
import { withApiLogging } from '../_shared/api-logger.ts';

const supabaseUrl = Deno.env.get('SUPABASE_URL') || '';
const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') || '';

Deno.serve(withApiLogging('generate-quote-pdf', async (req) => {
  // CORS preflight
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  const supabase = createClient(supabaseUrl, supabaseServiceKey);

  // Only accept POST
  if (req.method !== 'POST') {
    return jsonResponse({ success: false, error: 'Method not allowed' }, 405);
  }

  // Authenticate
  const auth = await authenticate(req);
  if (!auth.success) {
    return jsonResponse({ success: false, error: auth.error || 'Unauthorized' }, 401);
  }

  let quoteId: string;

  try {
    const body: QuotePDFRequest = await req.json();
    quoteId = body.quote_id;

    if (!quoteId) {
      return jsonResponse({ success: false, error: 'Missing quote_id' }, 400);
    }

    // Check if PDF already exists and regeneration not requested
    if (!body.regenerate) {
      const { data: existing } = await supabase
        .from('quotes')
        .select('pdf_storage_path, pdf_generation_status')
        .eq('id', quoteId)
        .single();

      if (existing?.pdf_storage_path && existing?.pdf_generation_status === 'completed') {
        // Refresh signed URL and return existing
        const { data: signedUrl } = await supabase.storage
          .from('pdf-documents')
          .createSignedUrl(existing.pdf_storage_path, 60 * 60 * 24 * 7);

        return jsonResponse({
          success: true,
          pdf_url: signedUrl?.signedUrl,
          pdf_storage_path: existing.pdf_storage_path,
        });
      }
    }

    // Mark as generating (this also triggers the quote_number auto-generation)
    await supabase
      .from('quotes')
      .update({
        pdf_generation_status: 'generating',
        updated_at: new Date().toISOString(),
      })
      .eq('id', quoteId);

    // Fetch all data
    const [quoteData, templateConfig] = await Promise.all([
      fetchQuoteData(supabase, quoteId),
      fetchTemplateConfig(supabase),
    ]);

    // Re-fetch quote_number (may have been generated by trigger)
    const { data: updatedQuote } = await supabase
      .from('quotes')
      .select('quote_number')
      .eq('id', quoteId)
      .single();

    if (updatedQuote?.quote_number) {
      quoteData.quote_number = updatedQuote.quote_number;
    }

    // Fetch template images in parallel
    const [coverBytes, bgBytes, backcoverBytes] = await Promise.all([
      fetchStorageFile(supabase, 'quote-templates', templateConfig.cover_image_path),
      fetchStorageFile(supabase, 'quote-templates', templateConfig.items_background_path),
      fetchStorageFile(supabase, 'quote-templates', templateConfig.backcover_image_path),
    ]);

    // Build the PDF
    const pdfBytes = await buildQuotePDF(
      quoteData,
      templateConfig,
      coverBytes,
      bgBytes,
      backcoverBytes
    );

    // Upload to storage
    const storagePath = `quote-output/${quoteId}/quote-${quoteData.quote_number || quoteId}.pdf`;
    const { error: uploadError } = await supabase.storage
      .from('pdf-documents')
      .upload(storagePath, pdfBytes, {
        contentType: 'application/pdf',
        upsert: true,
      });

    if (uploadError) {
      throw new Error(`Failed to upload PDF: ${uploadError.message}`);
    }

    // Generate signed URL (7-day expiry)
    const { data: signedUrl } = await supabase.storage
      .from('pdf-documents')
      .createSignedUrl(storagePath, 60 * 60 * 24 * 7);

    // Update quote record
    await supabase
      .from('quotes')
      .update({
        pdf_storage_path: storagePath,
        pdf_generated_at: new Date().toISOString(),
        pdf_generation_status: 'completed',
        updated_at: new Date().toISOString(),
      })
      .eq('id', quoteId);

    // Notify quote owner that PDF is ready
    const { data: quoteRecord } = await supabase
      .from('quotes')
      .select('user_id')
      .eq('id', quoteId)
      .single();
    if (quoteRecord?.user_id) {
      supabase.from('user_notifications').insert({
        user_id: quoteRecord.user_id,
        type: 'pdf_ready',
        title: 'Your quote PDF is ready',
        body: `Quote ${quoteData.quote_number || ''} PDF has been generated and is ready to download.`,
        action_url: `/quotes/${quoteId}`,
        is_read: false,
        metadata: { quote_id: quoteId },
      }).then(() => {});
    }

    const response: QuotePDFResponse = {
      success: true,
      quote_number: quoteData.quote_number || undefined,
      pdf_url: signedUrl?.signedUrl,
      pdf_storage_path: storagePath,
    };

    return jsonResponse(response);
  } catch (error) {
    console.error('PDF generation error:', error);

    // Mark failure
    if (quoteId!) {
      await supabase
        .from('quotes')
        .update({
          pdf_generation_status: 'failed',
          updated_at: new Date().toISOString(),
        })
        .eq('id', quoteId);
    }

    return jsonResponse(
      {
        success: false,
        error: error instanceof Error ? error.message : 'PDF generation failed',
      },
      500
    );
  }
}));

function jsonResponse(body: QuotePDFResponse, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  });
}
