// deno-lint-ignore-file no-explicit-any
// Payslip PDF generation. For each item in an (approved/paid) payroll run, render a one-page
// A4 payslip and file it into hr_documents (doc_type='payslip') so the employee sees it in /my-hr.
import { PDFDocument, rgb } from 'pdf-lib';
import { formatMoney } from '../_shared/money.ts';
import { embedOpenSans } from '../_shared/fonts/open-sans.ts';
import { corsHeaders } from '../_shared/cors.ts';
import { HttpError } from '../_shared/api-logger.ts';

const HR_DOC_BUCKET = 'pdf-documents';
// Was "1,234.56 EUR"; now matches the leading-symbol form the HR screens use.
const money = (n: number, c: string) => formatMoney(n ?? 0, c);

function json(body: any, status = 200): Response {
  return new Response(JSON.stringify(body), { status, headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
}

async function buildPayslip(opts: {
  company: string; period: string; employeeName: string; currency: string;
  gross: number; employeeEfka: number; incomeTax: number; net: number; employerEfka: number; employerCost: number;
  basisLabel: string;
  /** Employer identity from finance_settings — same source as every other document. */
  companyVat?: string | null; companyAddress?: string | null; companyLogo?: Uint8Array | null;
}): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const { regular: font, bold } = await embedOpenSans(pdf, { subset: false }); // text drawn after embed; keep all glyphs (Greek ΦΜΥ, −, ×)
  const page = pdf.addPage([595.28, 841.89]); // A4
  const W = 595.28;
  const ink = rgb(0.12, 0.12, 0.18), muted = rgb(0.45, 0.45, 0.5), line = rgb(0.85, 0.85, 0.88), accent = rgb(0.20, 0.60, 0.36);
  let y = 800;
  const text = (s: string, x: number, yy: number, size = 10, f = font, color = ink) => page.drawText(s, { x, y: yy, size, font: f, color });
  const right = (s: string, xRight: number, yy: number, size = 10, f = font, color = ink) => page.drawText(s, { x: xRight - f.widthOfTextAtSize(s, size), y: yy, size, font: f, color });

  // Employer logo (top-right, above the PAYSLIP label) when the business has one set.
  let logoH = 0;
  if (opts.companyLogo) {
    try {
      const img = await (async () => {
        try { return await pdf.embedPng(opts.companyLogo as Uint8Array); }
        catch { return await pdf.embedJpg(opts.companyLogo as Uint8Array); }
      })();
      const s = Math.min(110 / img.width, 36 / img.height);
      page.drawImage(img, { x: W - 40 - img.width * s, y: y - img.height * s + 12, width: img.width * s, height: img.height * s });
      logoH = img.height * s;
    } catch { /* logo optional */ }
  }
  text(opts.company, 40, y, 15, bold);
  if (!logoH) text('PAYSLIP', W - 40 - bold.widthOfTextAtSize('PAYSLIP', 15), y, 15, bold, muted);
  // Employer identity (VAT / address) — a payslip names the employer.
  const idBits = [opts.companyVat ? `VAT ${opts.companyVat}` : '', opts.companyAddress || ''].filter(Boolean).join('  ·  ');
  if (idBits) { y -= 13; text(idBits, 40, y, 8, font, muted); }
  if (logoH) { y -= 4; text('PAYSLIP', W - 40 - bold.widthOfTextAtSize('PAYSLIP', 11), y, 11, bold, muted); }
  y -= 18; text(`Pay period ${opts.period}`, 40, y, 10, font, muted);
  y -= 26; page.drawLine({ start: { x: 40, y }, end: { x: W - 40, y }, thickness: 1, color: line });
  y -= 22; text('Employee', 40, y, 9, font, muted); text(opts.employeeName, 40, y - 14, 12, bold);
  right('Basis', W - 40, y, 9, font, muted); right(opts.basisLabel, W - 40, y - 14, 11, font);
  y -= 44; page.drawLine({ start: { x: 40, y }, end: { x: W - 40, y }, thickness: 1, color: line });

  // Earnings & deductions
  y -= 26; text('Earnings & deductions', 40, y, 11, bold);
  const rowsCol = (label: string, val: string, strong = false) => {
    y -= 20; text(label, 48, y, 10, strong ? bold : font, strong ? ink : muted);
    right(val, W - 48, y, 10, strong ? bold : font);
  };
  rowsCol('Gross pay', money(opts.gross, opts.currency), true);
  rowsCol('Employee EFKA (social security)', `− ${money(opts.employeeEfka, opts.currency)}`);
  rowsCol('Income tax withheld (ΦΜΥ)', `− ${money(opts.incomeTax, opts.currency)}`);
  y -= 8; page.drawLine({ start: { x: 48, y }, end: { x: W - 48, y }, thickness: 1, color: line });
  y -= 22; text('Net pay', 48, y, 12, bold, accent); right(money(opts.net, opts.currency), W - 48, y, 12, bold, accent);

  // Employer cost (informational)
  y -= 40; text('Employer cost (not deducted from you)', 40, y, 11, bold);
  rowsCol('Employer EFKA contribution', money(opts.employerEfka, opts.currency));
  rowsCol('Total employer cost', money(opts.employerCost, opts.currency), true);

  y = 60; page.drawLine({ start: { x: 40, y }, end: { x: W - 40, y }, thickness: 1, color: line });
  y -= 16; text('This payslip is an estimate generated by the HR module. Statutory figures are configurable per workspace.', 40, y, 7.5, font, muted);
  return await pdf.save();
}

/** generate-payslips {run_id}: builds a payslip per item, stores it, and files an hr_documents row. */
export async function generatePayslips(supabase: any, workspaceId: string, userId: string, runId: string): Promise<Response> {
  const { data: run } = await supabase.from('hr_payroll_runs').select('*').eq('id', runId).eq('workspace_id', workspaceId).maybeSingle();
  if (!run) return json({ error: 'not found' }, 404);
  if (run.status === 'draft') return json({ error: 'Approve the run before generating payslips.' }, 400);

  const { data: ws } = await supabase.from('workspaces').select('name').eq('id', workspaceId).maybeSingle();
  // Employer identity = finance_settings business identity (the SAME source invoices,
  // quotes and receipts use), falling back to the workspace name.
  const { data: fsRow } = await supabase.from('finance_settings')
    .select('business_name, business_logo_path, business_vat, business_address, business_street_number, business_postal_code, business_city')
    .eq('workspace_id', workspaceId).maybeSingle();
  const f = (fsRow ?? {}) as Record<string, string | null>;
  const company = f.business_name || ws?.name || 'Company';
  const companyVat = f.business_vat || null;
  const companyAddress = [
    [f.business_address, f.business_street_number].filter(Boolean).join(' '),
    [f.business_postal_code, f.business_city].filter(Boolean).join(', '),
  ].filter(Boolean).join(', ') || null;
  let companyLogo: Uint8Array | null = null;
  if (f.business_logo_path) {
    try {
      const { data: lf } = await supabase.storage.from('generation-images').download(f.business_logo_path);
      if (lf) companyLogo = new Uint8Array(await lf.arrayBuffer());
    } catch { /* logo optional */ }
  }
  const { data: items } = await supabase.from('hr_payroll_items')
    .select('employee_id, gross, net, employee_contributions, income_tax, employer_contributions, employer_cost, currency, basis, rate, hours_per_day, days_worked, employee:hr_employees!hr_payroll_items_employee_id_fkey ( contact:crm_contacts!hr_employees_crm_contact_id_fkey ( name ) )')
    .eq('run_id', runId);

  let count = 0;
  for (const it of (items ?? [])) {
    const cur = it.currency || run.currency || 'EUR';
    const name = (it as any).employee?.contact?.name || 'Employee';
    const basisLabel = it.basis === 'hourly'
      ? `${money(Number(it.rate ?? 0), cur)}/h × ${it.hours_per_day ?? 8}h × ${it.days_worked ?? 0}d`
      : 'Monthly';
    const bytes = await buildPayslip({
      company, companyVat, companyAddress, companyLogo,
      period: run.period, employeeName: name, currency: cur,
      gross: Number(it.gross), employeeEfka: Number(it.employee_contributions), incomeTax: Number(it.income_tax),
      net: Number(it.net), employerEfka: Number(it.employer_contributions), employerCost: Number(it.employer_cost),
      basisLabel,
    });
    const path = `hr/${workspaceId}/${it.employee_id}/payslip-${run.period}.pdf`;
    const { error: upErr } = await supabase.storage.from(HR_DOC_BUCKET).upload(path, bytes, { contentType: 'application/pdf', upsert: true });
    if (upErr) throw new HttpError(400, `Payslip upload failed: ${upErr.message}`);
    // Replace any prior payslip row for this exact object, then file a fresh hr_documents record.
    await supabase.from('hr_documents').delete().eq('workspace_id', workspaceId).eq('storage_object_path', path);
    await supabase.from('hr_documents').insert({
      workspace_id: workspaceId, employee_id: it.employee_id, name: `Payslip ${run.period}`, doc_type: 'payslip',
      storage_bucket: HR_DOC_BUCKET, storage_object_path: path, size_bytes: bytes.length, uploaded_by: userId,
    });
    count++;
  }
  return json({ ok: true, payslips: count });
}
