/**
 * Plan geometry — the single place that turns a picture into measurements.
 *
 * Every plan backdrop the platform can obtain is a RASTER: either uploaded by
 * the user, or generated by Gemini through the `floor-plan-text` mode. Neither
 * carries a machine-readable scale, and the AI-generated one's printed dimension
 * callouts are decorative — the prompt asks for them, but an image generator
 * draws plausible numbers, not accurate ones. They must never be read back as a
 * measurement source.
 *
 * So scale is established exactly one way: the user calibrates a single line of
 * known real length, and `mm_per_px` falls out of it. `PlanCalibration` keeps
 * the evidence alongside the answer so the number can be re-derived and audited
 * rather than trusted.
 *
 * Everything here is pure. Persistence lives in projectsService; the canvas and
 * the PDF builder read through this module rather than destructuring the raw
 * jsonb, so the backing store can later be swapped for a real vector model
 * without touching either.
 *
 * UNITS: every stored coordinate is MILLIMETRES. Normalized [0..1] coordinates
 * cannot express a length, and every calculation downstream of this — cable run,
 * pipe fall, illuminance grid — needs one. The legacy symbol plans store
 * normalized coords; convert at the boundary with normalizedToMm / mmToNormalized
 * rather than mixing the two in one structure.
 */

export const PLAN_GEOMETRY_VERSION = 1;

export interface PlanCalibration {
  /** The two ends of the drawn reference line, in BACKDROP PIXELS. */
  x1: number;
  y1: number;
  x2: number;
  y2: number;
  /** What the user said that line measures in reality. */
  real_mm: number;
}

export interface PlanScale {
  mm_per_px: number;
  calibration?: PlanCalibration;
}

export interface PlanWall {
  id: string;
  /** Millimetres, origin at the backdrop's top-left. */
  x1: number;
  y1: number;
  x2: number;
  y2: number;
}

export type OpeningKind = 'door' | 'window' | 'opening';

export interface PlanOpening {
  id: string;
  wall_id: string;
  /** Distance from the wall's (x1,y1) end, in mm. */
  offset_mm: number;
  width_mm: number;
  kind: OpeningKind;
}

export interface PlanGeometry {
  version: number;
  /** Absent until the user calibrates. Consumers MUST handle the uncalibrated case. */
  scale?: PlanScale;
  walls: PlanWall[];
  openings: PlanOpening[];
}

export const EMPTY_PLAN_GEOMETRY: PlanGeometry = {
  version: PLAN_GEOMETRY_VERSION,
  walls: [],
  openings: [],
};

const isFiniteNumber = (v: unknown): v is number => typeof v === 'number' && Number.isFinite(v);

/**
 * Defensively read the jsonb column. Anything malformed degrades to "no
 * geometry" rather than throwing — a broken plan should render an empty canvas
 * the user can fix, not white-screen the room page.
 */
export function parsePlanGeometry(raw: unknown): PlanGeometry {
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return { ...EMPTY_PLAN_GEOMETRY };
  const o = raw as Record<string, unknown>;

  const walls: PlanWall[] = Array.isArray(o.walls)
    ? (o.walls as unknown[]).filter((w): w is PlanWall => {
        const c = w as Record<string, unknown> | null;
        return !!c && typeof c.id === 'string'
          && isFiniteNumber(c.x1) && isFiniteNumber(c.y1)
          && isFiniteNumber(c.x2) && isFiniteNumber(c.y2);
      })
    : [];

  const wallIds = new Set(walls.map((w) => w.id));
  const openings: PlanOpening[] = Array.isArray(o.openings)
    ? (o.openings as unknown[]).filter((op): op is PlanOpening => {
        const c = op as Record<string, unknown> | null;
        return !!c && typeof c.id === 'string' && typeof c.wall_id === 'string'
          // An opening whose wall is gone is orphaned geometry — drop it rather
          // than render a doorway floating in space.
          && wallIds.has(c.wall_id)
          && isFiniteNumber(c.offset_mm) && isFiniteNumber(c.width_mm) && c.width_mm > 0
          && (c.kind === 'door' || c.kind === 'window' || c.kind === 'opening');
      })
    : [];

  let scale: PlanScale | undefined;
  const rawScale = o.scale as Record<string, unknown> | undefined;
  if (rawScale && isFiniteNumber(rawScale.mm_per_px) && rawScale.mm_per_px > 0) {
    const rawCal = rawScale.calibration as Record<string, unknown> | undefined;
    const calibration: PlanCalibration | undefined =
      rawCal && isFiniteNumber(rawCal.x1) && isFiniteNumber(rawCal.y1)
        && isFiniteNumber(rawCal.x2) && isFiniteNumber(rawCal.y2)
        && isFiniteNumber(rawCal.real_mm) && rawCal.real_mm > 0
        ? { x1: rawCal.x1, y1: rawCal.y1, x2: rawCal.x2, y2: rawCal.y2, real_mm: rawCal.real_mm }
        : undefined;
    scale = { mm_per_px: rawScale.mm_per_px, ...(calibration ? { calibration } : {}) };
  }

  return {
    version: isFiniteNumber(o.version) ? o.version : PLAN_GEOMETRY_VERSION,
    ...(scale ? { scale } : {}),
    walls,
    openings,
  };
}

/**
 * Derive mm-per-pixel from a calibration line.
 *
 * Returns null — never 0 — when the input can't produce a scale. A zero scale
 * would flow silently into every downstream length as "0 mm" and look like a
 * legitimate answer; an explicit null forces the caller to handle it.
 */
export function calibrateFromLine(cal: PlanCalibration): number | null {
  if (!isFiniteNumber(cal.real_mm) || cal.real_mm <= 0) return null;
  const lengthPx = Math.hypot(cal.x2 - cal.x1, cal.y2 - cal.y1);
  // A line under a pixel is a stray click, not a measurement — and it would
  // produce an enormous mm_per_px that poisons every derived length.
  if (!Number.isFinite(lengthPx) || lengthPx < 1) return null;
  return cal.real_mm / lengthPx;
}

/** The calibrated scale, or null when the plan has not been calibrated yet. */
export function mmPerPx(geometry: PlanGeometry): number | null {
  const s = geometry.scale?.mm_per_px;
  return isFiniteNumber(s) && s > 0 ? s : null;
}

export function isCalibrated(geometry: PlanGeometry): boolean {
  return mmPerPx(geometry) !== null;
}

/** Apply a calibration line, returning updated geometry (or null if unusable). */
export function withCalibration(geometry: PlanGeometry, cal: PlanCalibration): PlanGeometry | null {
  const scale = calibrateFromLine(cal);
  if (scale === null) return null;
  return { ...geometry, scale: { mm_per_px: scale, calibration: cal } };
}

export function pxToMm(px: number, scale: number): number {
  return px * scale;
}

export function mmToPx(mm: number, scale: number): number {
  return mm / scale;
}

/**
 * Boundary conversion for the legacy symbol plans, which store positions as
 * normalized [0..1] over the backdrop extent. Keeps already-created lighting /
 * plumbing / electrical sheets rendering unchanged while new geometry is in mm.
 */
export function normalizedToMm(n: number, extentPx: number, scale: number): number {
  return n * extentPx * scale;
}

export function mmToNormalized(mm: number, extentPx: number, scale: number): number {
  const extentMm = extentPx * scale;
  if (extentMm <= 0) return 0;
  return mm / extentMm;
}

/** Floor area the calibration implies for a backdrop of the given pixel size. */
export function impliedAreaSqm(widthPx: number, heightPx: number, scale: number): number | null {
  if (!isFiniteNumber(widthPx) || !isFiniteNumber(heightPx) || widthPx <= 0 || heightPx <= 0) return null;
  if (!isFiniteNumber(scale) || scale <= 0) return null;
  return (widthPx * scale / 1000) * (heightPx * scale / 1000);
}

/**
 * Cross-check a calibration against the area the brief asked for.
 *
 * The agent-generated plan path already knows the requested `sqm`, so a
 * calibration that implies 400 m² for a 40 m² brief is almost certainly a
 * mistyped reference length. Warn — never silently correct; the user may be
 * calibrating against a plan that genuinely differs from the brief.
 */
export interface AreaCheck {
  implied_sqm: number;
  expected_sqm: number;
  ratio: number;
  suspicious: boolean;
}

export function checkAreaAgainstBrief(
  impliedSqm: number,
  expectedSqm: number,
  tolerance = 2,
): AreaCheck | null {
  if (!isFiniteNumber(impliedSqm) || impliedSqm <= 0) return null;
  if (!isFiniteNumber(expectedSqm) || expectedSqm <= 0) return null;
  const ratio = impliedSqm / expectedSqm;
  return {
    implied_sqm: impliedSqm,
    expected_sqm: expectedSqm,
    ratio,
    // Off by more than the tolerance factor in either direction. Default 2x —
    // loose enough for a plan that includes surrounding rooms, tight enough to
    // catch a metres-vs-millimetres slip (1000x) or a wrong wall.
    suspicious: ratio > tolerance || ratio < 1 / tolerance,
  };
}

/** Wall length in mm. */
export function wallLengthMm(w: PlanWall): number {
  return Math.hypot(w.x2 - w.x1, w.y2 - w.y1);
}

/** Total traced wall run, in metres — the first genuinely derived quantity. */
export function totalWallRunM(geometry: PlanGeometry): number {
  return geometry.walls.reduce((sum, w) => sum + wallLengthMm(w), 0) / 1000;
}
