/**
 * The cast is the PERMANENT avatar for every WhatsApp contact — WhatsApp gives a business no
 * customer profile picture on any endpoint that declares the field (measured 0/100 conversations,
 * 0/516 contacts). So assignment being stable and every slot actually existing is the feature,
 * not polish, and neither raises anything when it breaks: a 404 avatar just renders as nothing.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { CAST_SIZE, castSlotFor, castObjectFor, castAvatarUrl } from '../../src/utils/characterAvatar';

const API = readFileSync(
  join(process.cwd(), 'supabase', 'functions', 'messaging-api', 'index.ts'), 'utf8');

describe('character avatar cast', () => {
  it('never points a contact at a slot that was never rendered', () => {
    // CAST_SIZE too high = some contacts resolve to a 404, which renders as an empty avatar and
    // reports nothing — the exact silent state this feature exists to end. 24 slots (000-023)
    // were generated by `generate-avatar-cast`.
    expect(CAST_SIZE).toBe(24);
    const slots = new Set(
      Array.from({ length: 3000 }, (_, i) => castSlotFor(`contact-${i}`)),
    );
    expect(Math.max(...slots)).toBeLessThan(CAST_SIZE);
    expect(Math.min(...slots)).toBeGreaterThanOrEqual(0);
    // And the generator pads to three digits, so the consumer must expect the same.
    expect(API).toMatch(/String\(slot\)\.padStart\(3, '0'\)/);
    expect(castObjectFor('c-1').storage_object_path).toMatch(/^avatars\/cast\/\d{3}\.png$/);
  });

  it('spreads contacts across the whole cast', () => {
    // A hash that clustered would give half the inbox one face, which looks broken in a way
    // nothing would flag.
    const used = new Set(Array.from({ length: 400 }, (_, i) => castSlotFor(`wa-${i}`)));
    expect(used.size).toBe(CAST_SIZE);
  });

  it('is stable for an id, and keyed on the id rather than the name', () => {
    // A name gets corrected, re-capitalised, and arrives one way from WhatsApp and another from
    // the CRM. Seeding on it would hand people a new face every time their record is tidied.
    expect(castSlotFor('c-9')).toBe(castSlotFor('c-9'));
    expect(castObjectFor('c-9')).toEqual(castObjectFor('c-9'));
  });

  it('builds a PUBLIC url, never a signed one', () => {
    // The same face renders on every message row; a signed url would need constant re-minting
    // and would break mid-scroll the moment one expired.
    const url = castAvatarUrl('c-1', 'https://x.supabase.co/storage/v1');
    expect(url).toMatch(/\/object\/public\/generation-images\/avatars\/cast\/\d{3}\.png$/);
    expect(url).not.toMatch(/token=/);
  });

  it('generates into a fixed path per slot, so re-running replaces rather than accumulates', () => {
    // Otherwise every rejected iteration on the prompt stays in the bucket and assignment starts
    // handing them out alongside the ones that were kept.
    expect(API).toMatch(/upsert: true/);
    expect(API).toMatch(/avatars\/cast\//);
  });

  it('reports a partial render as partial', () => {
    // A safety refusal on one prompt or a rate limit is the normal failure here, and "9 of 12"
    // must not read as a complete cast.
    expect(API).toMatch(/made\.length === count/);
  });
});
