/**
 * The cast is the PERMANENT avatar for every WhatsApp contact — WhatsApp gives a business no
 * customer profile picture on any endpoint that declares the field (measured 0/100 conversations,
 * 0/516 contacts). So assignment being stable and every slot actually existing is the feature,
 * not polish, and neither raises anything when it breaks: a 404 avatar just renders as nothing.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  CAST_SIZE, castSlotFor, castObjectFor, castAvatarUrl,
  castSeedForThreadCounterparty, castSeedForSender,
} from '../../src/utils/characterAvatar';

const API = readFileSync(
  join(process.cwd(), 'supabase', 'functions', 'messaging-api', 'index.ts'), 'utf8');

describe('character avatar cast', () => {
  it('never points a contact at a slot that was never rendered', () => {
    // CAST_SIZE too high = some contacts resolve to a 404, which renders as an empty avatar and
    // reports nothing — the exact silent state this feature exists to end. 24 slots (000-023)
    // were generated by `generate-avatar-cast`.
    expect(CAST_SIZE).toBe(24);
    const slots = new Set(
      Array.from({ length: 3000 }, (_, i) => castSlotFor(`contact-${i}`)),
    );
    expect(Math.max(...slots)).toBeLessThan(CAST_SIZE);
    expect(Math.min(...slots)).toBeGreaterThanOrEqual(0);
    // And the generator pads to three digits, so the consumer must expect the same.
    expect(API).toMatch(/String\(slot\)\.padStart\(3, '0'\)/);
    expect(castObjectFor('c-1').storage_object_path).toMatch(/^avatars\/cast\/\d{3}\.png$/);
  });

  it('spreads contacts across the whole cast', () => {
    // A hash that clustered would give half the inbox one face, which looks broken in a way
    // nothing would flag.
    const used = new Set(Array.from({ length: 400 }, (_, i) => castSlotFor(`wa-${i}`)));
    expect(used.size).toBe(CAST_SIZE);
  });

  it('is stable for an id, and keyed on the id rather than the name', () => {
    // A name gets corrected, re-capitalised, and arrives one way from WhatsApp and another from
    // the CRM. Seeding on it would hand people a new face every time their record is tidied.
    expect(castSlotFor('c-9')).toBe(castSlotFor('c-9'));
    expect(castObjectFor('c-9')).toEqual(castObjectFor('c-9'));
  });

  it('builds a PUBLIC url, never a signed one', () => {
    // The same face renders on every message row; a signed url would need constant re-minting
    // and would break mid-scroll the moment one expired.
    const url = castAvatarUrl('c-1', 'https://x.supabase.co/storage/v1');
    expect(url).toMatch(/\/object\/public\/generation-images\/avatars\/cast\/\d{3}\.png$/);
    expect(url).not.toMatch(/token=/);
  });

  it('generates into a fixed path per slot, so re-running replaces rather than accumulates', () => {
    // Otherwise every rejected iteration on the prompt stays in the bucket and assignment starts
    // handing them out alongside the ones that were kept.
    expect(API).toMatch(/upsert: true/);
    expect(API).toMatch(/avatars\/cast\//);
  });

  it('reports a partial render as partial', () => {
    // A safety refusal on one prompt or a rate limit is the normal failure here, and "9 of 12"
    // must not read as a complete cast.
    expect(API).toMatch(/made\.length === count/);
  });
});

/**
 * One person is ONE face.
 *
 * The inbox draws a counterparty five times — list row, header, message rows, profile drawer,
 * details rail — and the seed decides which of the 24 characters they get. Two sites seeding
 * differently is two people on screen, and it is completely silent: both URLs load, both faces
 * are from the cast, both look designed. Thread `d3a43bcd…` shipped exactly that — its header
 * seeded on the thread id (`cast/016`, a woman) while every one of the man's messages seeded on
 * his participant id (`cast/021`).
 */
describe('one person is one face', () => {
  const THREAD = { id: 'd3a43bcd-1490-47c0-b10e-86e24ee8c37c' };
  const CUSTOMER = 'bed5590f-483c-414e-9501-6a0e56666ffd';

  it('gives the header and the message rows the same character', () => {
    const thread = { ...THREAD, counterparty_participant_id: CUSTOMER };
    const headerSeed = castSeedForThreadCounterparty(thread, 'Drosopoulos Dev.');
    const bubbleSeed = castSeedForSender({ sender_participant_id: CUSTOMER }, 'Drosopoulos Dev.');
    expect(headerSeed).toBe(bubbleSeed);
    // The seeds agreeing is the mechanism; the SLOT agreeing is what the operator sees.
    expect(castSlotFor(headerSeed)).toBe(castSlotFor(bubbleSeed));
  });

  it('is the historical regression, so the fix is watched to matter', () => {
    // Seeding the header on the thread id — what it used to do — picks a different character.
    // If this ever stops being true the test above has stopped proving anything.
    expect(castSlotFor(THREAD.id)).not.toBe(castSlotFor(CUSTOMER));
  });

  it('never seeds on the name, which is edited', () => {
    // A WhatsApp push name, then the CRM name, then a tidy-up: seeding on it is a new face each
    // time. The fallback is only reached when there is no participant AND no thread.
    const named = { id: 't-1', counterparty_participant_id: 'p-1' };
    expect(castSeedForThreadCounterparty(named, 'Κώστας')).toBe('p-1');
    expect(castSeedForThreadCounterparty({ ...named, counterparty_participant_id: null }, 'Κώστας')).toBe('t-1');
  });

  it('keeps two customers in one thread apart', () => {
    // One live thread has two customer participants. Collapsing the message rows onto the thread
    // id — the other way to make these agree — would draw both of them as the same person.
    expect(castSlotFor(castSeedForSender({ sender_participant_id: 'p-a' })))
      .not.toBe(castSlotFor(castSeedForSender({ sender_participant_id: 'p-b' })));
  });

  it('is derived server-side, not re-answered per screen', () => {
    // The mailbox list has no participants loaded, so if the field is not on the thread the list
    // silently falls back to the thread id and the face changes the moment you click the row.
    const EDGE = readFileSync(
      join(process.cwd(), 'supabase', 'functions', 'inbox-api', 'index.ts'), 'utf8');
    expect(EDGE).toMatch(/function counterpartyParticipantId/);
    // Both readers of a thread must attach it — list_threads for the row, get_thread for the header.
    expect(EDGE.match(/counterparty_participant_id/g)?.length ?? 0).toBeGreaterThanOrEqual(2);
  });
});
