/**
 * Guard for the 3D product viewer's placement math (#321).
 *
 * A model that loads but sits half-buried in the floor, floats off-centre, or
 * renders at 1/50th the frame is a *valid* render — nothing throws, no type is
 * wrong, and the swatch fallback never kicks in. Only looking at it catches
 * that, and nobody looks at every product. So this parses a REAL .glb with the
 * same GLTFLoader drei's `useGLTF` uses, runs the exported
 * `normalizeModelTransform` (the same function the component calls — not a copy
 * of the math), and asserts the placement invariants.
 *
 * Fixture: tests/fixtures/armchair.glb — authored at true real-world scale
 * (0.78 x 0.81 x 0.77 m) with named sub-meshes, regenerated by
 * tests/fixtures/make-armchair-glb.cjs. The sub-mesh names are asserted too
 * because the #260 configurator swaps materials per named part.
 */
import { describe, it, expect, beforeAll } from 'vitest';
import { readFileSync } from 'fs';
import path from 'path';
import { Box3, Vector3, type Group } from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { normalizeModelTransform, TARGET_SIZE } from '@/components/features/ar/ProductModelViewer';

const FIXTURE = path.resolve(__dirname, '../fixtures/armchair.glb');

let scene: Group;

beforeAll(async () => {
  const buf = readFileSync(FIXTURE);
  const ab = buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength) as ArrayBuffer;
  const gltf = await new Promise<any>((resolve, reject) =>
    new GLTFLoader().parse(ab, '', resolve, reject),
  );
  scene = gltf.scene;
});

/** Bounding box after applying the transform the way the <group> does. */
function placedBox(): Box3 {
  const { scale, offset } = normalizeModelTransform(scene);
  scene.scale.setScalar(scale);
  scene.position.copy(offset);
  scene.updateMatrixWorld(true);
  return new Box3().setFromObject(scene);
}

describe('product 3D model normalization', () => {
  it('parses a real GLB through the loader the viewer uses', () => {
    const meshes: string[] = [];
    scene.traverse((o: any) => { if (o.isMesh) meshes.push(o.name); });
    expect(meshes.length).toBeGreaterThan(0);
  });

  it('keeps named sub-meshes intact for per-part material swaps (#260)', () => {
    const meshes: string[] = [];
    scene.traverse((o: any) => { if (o.isMesh) meshes.push(o.name); });
    expect(meshes).toEqual(
      expect.arrayContaining(['frame', 'seat_cushion', 'back_cushion', 'armrest_left', 'armrest_right']),
    );
  });

  it('scales the largest dimension to exactly TARGET_SIZE', () => {
    const size = placedBox().getSize(new Vector3());
    expect(Math.max(size.x, size.y, size.z)).toBeCloseTo(TARGET_SIZE, 6);
  });

  it('rests the model on the floor rather than burying or floating it', () => {
    expect(placedBox().min.y).toBeCloseTo(0, 6);
  });

  it('centers the model on x and z so the turntable orbits its middle', () => {
    const center = placedBox().getCenter(new Vector3());
    expect(center.x).toBeCloseTo(0, 6);
    expect(center.z).toBeCloseTo(0, 6);
  });

  it('leaves the orbit target inside the model, not above or below it', () => {
    const box = placedBox();
    const orbitTargetY = TARGET_SIZE / 2 - 0.25;
    expect(orbitTargetY).toBeGreaterThan(box.min.y);
    expect(orbitTargetY).toBeLessThan(box.max.y);
  });

  it('normalizes a tiny model UP, not just a large one down', () => {
    // A 2 cm sample chip and a 4 m wardrobe must both fill the same frame —
    // the scale factor is a ratio, so guard the small-input direction too.
    const tiny = scene.clone();
    tiny.scale.setScalar(0.001);
    tiny.updateMatrixWorld(true);
    const { scale } = normalizeModelTransform(tiny);
    expect(scale).toBeGreaterThan(1);
    const box = new Box3().setFromObject(tiny);
    const size = box.getSize(new Vector3());
    expect(Math.max(size.x, size.y, size.z) * scale).toBeCloseTo(TARGET_SIZE, 6);
  });

  it('does not divide by zero on a degenerate (empty) scene', () => {
    const { scale, offset } = normalizeModelTransform(new (scene.constructor as any)());
    expect(Number.isFinite(scale)).toBe(true);
    expect(Number.isFinite(offset.x)).toBe(true);
    expect(Number.isFinite(offset.y)).toBe(true);
  });
});
