/**
 * Search-fold twin-parity guard.
 *
 * The CRM lists match a FOLDED query term against a FOLDED column: `crm_contacts.search_fold` /
 * `crm_companies.search_fold` are generated by `public.crm_fold()` on write, and the term is
 * folded in TypeScript on read. If the two sides stop agreeing on what "folded" means, they
 * simply never meet — the search returns nothing, no error, no log, and it reads as missing data.
 * That is the exact failure mode this repo already paid for once with escapeHtml.
 *
 * Three implementations of one algorithm, none of which can share a module:
 *   • src/components/core/filters/types.ts     — frontend (option-list search)
 *   • supabase/functions/_shared/searchFold.ts — Deno edge (server-side list search)
 *   • public.crm_fold(text)                    — SQL (writes the stored column)
 *
 * The two TypeScript twins are imported and compared for real. SQL cannot run here, so its half
 * is pinned by VECTORS — frozen output captured from `public.crm_fold()` against the live
 * database. If you change the algorithm, you change it in all three and re-capture:
 *
 *   select t, public.crm_fold(t) from (values ('…')) v(t);
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { foldForSearch as frontendFold } from '@/components/core/filters/types';
import { foldForSearch as edgeFold } from '../../supabase/functions/_shared/searchFold';

const IMPLS: Array<[string, (v: unknown) => string]> = [
  ['src/components/core/filters/types.ts', frontendFold],
  ['supabase/functions/_shared/searchFold.ts', edgeFold],
];

/** input → output, as produced by `public.crm_fold()` in Postgres. */
const VECTORS: Array<[string, string]> = [
  // Greek: the case this exists for. All five spellings of one name must land on one key.
  ['ΚΩΣΤΑΣ ΑΛΕΞΙΟΥ', 'κωστασ αλεξιου'],
  ['Κώστας', 'κωστασ'],
  ['κωστάς', 'κωστασ'],
  ['ΚΩΣΤΑΣ', 'κωστασ'],
  ['κωστασ', 'κωστασ'],
  ['Π ΣΚΕΠΕΤΑΡΗΣ ΚΑΙ ΣΙΑ ΕΕ', 'π σκεπεταρησ και σια εε'],
  ['ΑΓΓΕΛΟΣ', 'αγγελοσ'],
  // Every accented Greek vowel, both cases, plus the diaeresis and tonos+diaeresis forms.
  ['άέήίόύώ', 'αεηιουω'],
  ['ΆΈΉΊΌΎΏ', 'αεηιουω'],
  ['ΪΫϊϋΐΰ', 'ιυιυιυ'],
  // Latin diacritics.
  ['Société Générale', 'societe generale'],
  ['Botguard OÜ', 'botguard ou'],
  // Strip-then-lower, not lower-then-strip: İ (U+0130) decomposes to I + dot above. Get the
  // order wrong and JS emits 'i̇' (i + combining dot) while Postgres emits 'i' — a silent split.
  ['İstanbul', 'istanbul'],
  // Not a transliterator: Cyrillic stays Cyrillic (that is _shared/transliterate.ts).
  ['Трендафил Ташков', 'трендафил ташков'],
  ['Trendafil', 'trendafil'],
  // Real rows, punctuation included.
  ['ΧΟΝΔΡΙΚΟ ΕΜΠΟΡΙΟ ΠΛΑΚΑΚΙΩΝ, ΠΛΑΚΟΛΙΘΩΝ', 'χονδρικο εμποριο πλακακιων, πλακολιθων'],
  ['MODERN DESIGN 2025 ΜΟΝΟΠΡΟΣΩΠΗ Ι Κ Ε', 'modern design 2025 μονοπροσωπη ι κ ε'],
  ['KOLOMOLO Sp. z o.o.', 'kolomolo sp. z o.o.'],
  ['plain ascii', 'plain ascii'],
  ['', ''],
];

describe('foldForSearch — the twins agree with each other', () => {
  it.each(VECTORS.map(([input]) => [input || '(empty)', input]))(
    'both TypeScript implementations agree on %s',
    (_label, input) => {
      const [[refName, ref], ...rest] = IMPLS;
      for (const [name, fn] of rest) {
        expect(
          fn(input),
          `${name} diverged from ${refName} — the twins have drifted, which makes server search ` +
            `and option-list search disagree about what a term means.`,
        ).toBe(ref(input));
      }
    },
  );

  it('is total on nullish and non-string input', () => {
    for (const [name, fn] of IMPLS) {
      expect(fn(undefined), name).toBe('');
      expect(fn(null), name).toBe('');
      expect(fn(0), name).toBe('0');
    }
  });
});

describe('foldForSearch — the twins agree with public.crm_fold()', () => {
  it.each(VECTORS)('%s folds to the value Postgres stores', (input, expected) => {
    for (const [name, fn] of IMPLS) {
      expect(
        fn(input),
        `${name} no longer matches public.crm_fold(). The stored search_fold column is written ` +
          `by SQL and queried with this function — a mismatch means the query silently stops ` +
          `matching. Update crm_fold() in a migration and re-capture VECTORS.`,
      ).toBe(expected);
    }
  });

  it('folding is idempotent — a folded term folded again is unchanged', () => {
    // The stored column holds already-folded text; re-folding it must be a no-op or a second
    // pass anywhere in the chain would shift the haystack out from under the needle.
    for (const [name, fn] of IMPLS) {
      for (const [, folded] of VECTORS) expect(fn(folded), name).toBe(folded);
    }
  });
});

/**
 * The handlers must actually USE the folded column. Reverting one line to `.ilike('name', …)`
 * would restore the original bug while every test above still passed.
 */
describe('crm-api searches the folded column', () => {
  const read = (p: string) => readFileSync(join(process.cwd(), p), 'utf8');
  const HANDLERS = [
    'supabase/functions/crm-api/handlers/contacts-api-handler.ts',
    'supabase/functions/crm-api/handlers/companies-api-handler.ts',
  ];

  it.each(HANDLERS)('%s folds the term before matching', (path) => {
    const src = read(path);
    expect(src, 'handler no longer imports the canonical fold').toMatch(
      /import\s*\{[^}]*\bfoldForSearch\b[^}]*\}\s*from\s*['"][^'"]*searchFold\.ts['"]/,
    );
    expect(src, 'the search term is no longer folded').toMatch(/foldForSearch\(search\)/);
    expect(src, 'the query no longer targets search_fold').toContain('search_fold');
  });

  it('does not match the raw name/email columns for free-text search', () => {
    // `.eq('name', …)` for the exact company-name filter is fine; a `%…%` ilike on a raw
    // column is the accent-sensitive path this replaced.
    for (const path of HANDLERS) {
      expect(read(path), `${path} still ilikes a raw column`).not.toMatch(
        /\.ilike\(\s*['"](name|email|website)['"]/,
      );
      expect(read(path), `${path} still builds a raw-column or() search`).not.toMatch(
        /`(name|email|website)\.ilike\./,
      );
    }
  });
});
